//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewShop.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewShopEntities : DbContext
    {
        public NewShopEntities()
            : base("name=NewShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ManagerInfo> ns_managers { get; set; }
        public virtual DbSet<MenuInfo> ns_menu { get; set; }
        public virtual DbSet<RoleInfo> ns_role { get; set; }
    }
}
